services:
  geordi:
    build: .
    container_name: geordi
    restart: unless-stopped
    ports:
      - "5001:5001" # <-- CORRECTED PORT MAPPING
    volumes:
      - /opt/docker/geordi:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/geordi/data:/app/data # <-- CORRECTED VOLUME MAPPING
    environment:
      - TZ=America/Los_Angeles
      - PORT=5001
      - OLLAMA_API_URL=http://localhost:11434/api/generate
      - OLLAMA_MODEL=llama2-uncensored:7b
      - SCAN_INTERVAL_MINUTES=300 # Note: These are now defaults, overridden by DB settings
      - LOG_LINES_TO_FETCH=20     # Note: These are now defaults, overridden by DB settings
      - FLASK_SECRET_KEY=a_very_secret_and_unique_key_for_session_security # CHANGE THIS!

