services:
  geordi:
    build: .
    container_name: geordi
    restart: unless-stopped
    ports:
      - "5001:5000" # Map host port 5001 to container port 5000
    volumes:
      - /opt/docker/geordi:/app
      # Mount the Docker socket (REQUIRED)
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only is safer if sufficient
      # Mount a volume to persist the SQLite database
      - log_monitor_data:/app/monitoring_data.db
    environment:
      - TZ=America/Los_Angeles
      # --- Pass environment variables ---
      # For Docker Desktop (Mac/Win):
      - OLLAMA_API_URL=http://192.168.1.11:11434/api/generate
      # For Docker on Linux (use host IP or create a network, see notes):
      # - OLLAMA_API_URL=http://172.17.0.1:11434/api/generate
      - OLLAMA_MODEL=llama2-uncensored:7b # Or your preferred model
      - SCAN_INTERVAL_MINUTES=300
      - LOG_LINES_TO_FETCH=20
      - FLASK_SECRET_KEY=a_very_secret_and_unique_key_for_session_security # CHANGE THIS!
      # Optional: Set log level if needed (e.g., DEBUG)
      # - LOG_LEVEL=INFO
    # Optional: Define a network if Ollama is also in a container
    # networks:
    #   - monitor_net

volumes:
  log_monitor_data: # Docker managed volume for the DB

# Optional: Add Ollama service if you want to run it via compose too
# services:
#   ollama:
#     image: ollama/ollama
#     container_name: ollama
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama_data:/root/.ollama
#     restart: unless-stopped
#     networks:
#       - monitor_net # Ollama and monitor on the same network

# volumes:
#   ollama_data:

# networks:
#   monitor_net:
#     driver: bridge
